[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/hello-world"
  to = "/.netlify/functions/hello-world"
  status = 200

[[redirects]]
  from = "/api-tools"
  to = "/.netlify/functions/api-tools"
  status = 200

[[redirects]]
  from = "/advanced-example"  
  to = "/.netlify/functions/advanced-example"
  status = 200
