[build]
  command = "npm run build"
  functions = "netlify/functions"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/mcp"
  to = "/.netlify/functions/mcp"
  status = 200
